<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-xs font-semibold uppercase tracking-[0.16em] text-brand-600">Catálogo</p><h1 class="mt-1 text-2xl font-extrabold text-slate-950">Servicios</h1><p class="mt-1 text-sm text-slate-500">Administra precios, duración y comisiones.</p></div>@can('create', App\Models\Service::class)<a href="{{ route('services.create') }}" wire:navigate class="inline-flex items-center justify-center rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-brand-700">+ Nuevo servicio</a>@endcan</div>

    @if (session('status')) <div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('status') }}</div> @endif

    <div class="rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div class="grid gap-3 border-b border-slate-200 p-4 sm:grid-cols-[minmax(0,1fr)_180px]"><input type="search" wire:model.live.debounce.350ms="search" placeholder="Buscar por nombre o descripción..." class="rounded-xl border-slate-300 text-sm focus:border-brand-500 focus:ring-brand-500"><select wire:model.live="status" class="rounded-xl border-slate-300 text-sm focus:border-brand-500 focus:ring-brand-500"><option value="all">Todos</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select></div>
        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200">
            <thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left text-xs font-bold uppercase text-slate-500">Servicio</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-slate-500">Duración</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-slate-500">Precio</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-slate-500">Comisión</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-slate-500">Estado</th><th class="px-5 py-3 text-right text-xs font-bold uppercase text-slate-500">Acciones</th></tr></thead>
            <tbody class="divide-y divide-slate-100">
            @forelse ($services as $service)
                <tr wire:key="service-{{ $service->id }}" class="hover:bg-slate-50"><td class="px-5 py-4"><a href="{{ route('services.show', $service) }}" wire:navigate class="text-sm font-semibold text-slate-900 hover:text-brand-600">{{ $service->name }}</a><p class="max-w-sm truncate text-xs text-slate-500">{{ $service->description }}</p></td><td class="whitespace-nowrap px-5 py-4 text-sm text-slate-700">{{ $service->duration_minutes }} min</td><td class="whitespace-nowrap px-5 py-4 text-sm font-semibold text-slate-900">${{ number_format((float) $service->price, 2) }}</td><td class="whitespace-nowrap px-5 py-4 text-sm text-slate-700">{{ number_format((float) $service->commission_percentage, 2) }}%</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $service->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $service->is_active ? 'Activo' : 'Inactivo' }}</span></td><td class="whitespace-nowrap px-5 py-4 text-right"><a href="{{ route('services.show', $service) }}" wire:navigate class="px-2 py-1 text-xs font-semibold text-slate-600">Ver</a>@can('update', $service)<a href="{{ route('services.edit', $service) }}" wire:navigate class="px-2 py-1 text-xs font-semibold text-brand-700">Editar</a><button wire:click="changeStatus({{ $service->id }})" wire:confirm="¿Cambiar el estado de {{ $service->name }}?" class="px-2 py-1 text-xs font-semibold text-red-600">{{ $service->is_active ? 'Desactivar' : 'Activar' }}</button>@endcan</td></tr>
            @empty <tr><td colspan="6" class="px-5 py-14 text-center text-sm text-slate-500">No se encontraron servicios.</td></tr> @endforelse
            </tbody>
        </table></div>
        @if ($services->hasPages()) <div class="border-t border-slate-200 px-5 py-4">{{ $services->links() }}</div> @endif
    </div>
</div>
